- name: Update Ubuntu OS
  apt:
    upgrade: "yes"
    update_cache: "yes"
  #Install NGINX
- name: Installing nginx
  apt:
    name: nginx
    state: latest
  
# Start the NGINX service after installation
- name: ensure NGINX is running
  service:
    name: nginx
    state: started

  # Install Nodejs
- name: Installing the gpg key for nodejs LTS
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Install NODEJS LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes 

- name: Installing NODEJS
  apt: 
    name: nodejs
    state: present

# Install PM2 for background process running
- name: Install PM2
  command: npm install -g pm2
